language: python
python:
  - "2.7"
  - "3.4"
before_install:
  # We need GraphViz
install:
  - pip install nose
  - pip install coveralls
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=dotmap
after_success:
  - coveralls